### ISSUE TITLE
Thanks for your sharing, but why the larger angle, the worse acc? I could not figure it out 

### ISSUE THREAD

**Issue by whrenstone** [YeahHuang/Al_surface_defect_detection#15]

**Comment by YeahHuang** [comment]
By carefully looking at the aluminum pictures in the dataset, I later found out that it was because the angle between the aluminum strip and the horizontal line was not very large. So when you are rotating too large angles, it is actually generating noise data that does not exist in both the training datasets and test datasets. That's why I found in the step of adding noise data for better model robustness,  0-8 degrees is the ideal rotation angle.
