### ISSUE TITLE
How to do bbox voting using bbox-vote strategy like ID, AVG, IOU_AVG

### ISSUE THREAD

**Issue by Bigwode** [YeahHuang/Al_surface_defect_detection#7]

**Comment by jiec-msft** [comment]
You need to understand that the yaml files in the directory `configs\12_2017_baselines` will be merged into the file `config.py` in the `detectron\core\config.py`

So, please refer to the Chinese URL like: [https://blog.csdn.net/zziahgf/article/details/79652946](https://blog.csdn.net/zziahgf/article/details/79652946), or read the comments in the file `detectron\core\config.py`.    
For a quick look of related contents inside the file `config.py`: 
```
# ---------------------------------------------------------------------------- #
# Test-time augmentations for bounding box detection
# See configs/test_time_aug/e2e_mask_rcnn_R-50-FPN_2x.yaml for an example
# ---------------------------------------------------------------------------- #
__C.TEST.BBOX_AUG = AttrDict()

# Enable test-time augmentation for bounding box detection if True
__C.TEST.BBOX_AUG.ENABLED = False

# Heuristic used to combine predicted box scores
#   Valid options: ('ID', 'AVG', 'UNION')
__C.TEST.BBOX_AUG.SCORE_HEUR = 'UNION'

# Heuristic used to combine predicted box coordinates
#   Valid options: ('ID', 'AVG', 'UNION')
__C.TEST.BBOX_AUG.COORD_HEUR = 'UNION'

# Horizontal flip at the original scale (id transform)
__C.TEST.BBOX_AUG.H_FLIP = False

# Each scale is the pixel size of an image's shortest side
__C.TEST.BBOX_AUG.SCALES = ()

# Max pixel size of the longer side
__C.TEST.BBOX_AUG.MAX_SIZE = 4000

# Horizontal flip at each scale
__C.TEST.BBOX_AUG.SCALE_H_FLIP = False

# Apply scaling based on object size
__C.TEST.BBOX_AUG.SCALE_SIZE_DEP = False
__C.TEST.BBOX_AUG.AREA_TH_LO = 50**2
__C.TEST.BBOX_AUG.AREA_TH_HI = 180**2

# Each aspect ratio is relative to image width
__C.TEST.BBOX_AUG.ASPECT_RATIOS = ()

# Horizontal flip at each aspect ratio
__C.TEST.BBOX_AUG.ASPECT_RATIO_H_FLIP = False
```


Best wishes

**Comment by jiec-msft** [comment]
BTW, you can get the dataset here: 
```
URL：https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA 
password：w7tn
```

**Comment by Bigwode** [comment]
@ECNUJason Thanks, this is used for bounding box voting before and after NMS，but what I want is how to change this used for two model's predicted bounding box voting?

**Comment by YeahHuang** [comment]
> @ECNUJason Thanks, this is used for bounding box voting before and after NMS，but what I want is how to change this used for two model's predicted bounding box voting?

It's the same.    
Predicted bounding box voting is also changed in the yaml. It has to be combined with NMS.   And u need to carefully understand config.py before changing it.

**Comment by Bigwode** [comment]
@ECNUJason Thanks for your patience

**Comment by jiec-msft** [comment]
You are welcome. @Bigwode

**Comment by sxlyiyiyi** [comment]
> 可以
请问有数据集的标注文件吗

**Comment by sxlyiyiyi** [comment]
> BTW, you can get the dataset here:
> 
> ```
> URL：https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA 
> password：w7tn
> ```

请问有数据集的标注文件吗

**Comment by jiec-msft** [comment]
sry, it’s been too long that i’ve already deleted everything on my hard disk ---- Replied Message ***@***.***>Date05/10/2021 10:44 ***@***.***> ***@***.******@***.***>SubjectRe: [YeahHuang/Al_surface_defect_detection] How to do bbox voting using bbox-vote strategy like ID, AVG, IOU_AVG (#7)



BTW, you can get the dataset here:

URL：https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA  

password：w7tn





请问有数据集的标注文件吗



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/YeahHuang/Al_surface_defect_detection/issues/7#issuecomment-836089568",

"url": "https://github.com/YeahHuang/Al_surface_defect_detection/issues/7#issuecomment-836089568",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Hahahdamowang** [comment]
> > 顺便说一句，您可以在此处获取数据集：
> > ```
> > URL：https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA 
> > password：w7tn
> > ```
> 
> 有数据集的标签文件吗？

你好请问数据集的标签文件吗？感谢
